#DC = {}
Label = "test_label"
Textbox = "test_input"
Button = "test_button"
CalendarDayButton = "test_calendarDayButton"
PopUpCaption = "test_popupCaption"
AutocompleteDropDown = "test_autocompleteDropDown"
PopupCalendar = "test_popupCalendar"
Tab = "test_tabs"
Table = "test_table"
ErrorStatusMsg = "test_errorstatusmsg"
Link = "test_link"
Toplink = "test_toplink"
Checkbox = "test_checkbox"
TopMenu = "test_topMenu"
TopMenuText = "topMenu_text"
Dropdown = "test_select"
Multiselect = "test_multiselect"
RadioButton ="test_radioButton"
Time = "test_time"
Text = "test_text"
Textarea = "test_textArea"
Loading = "test_loading"
Notification = "test_notification"
Icon = "test_icon"
OMChart = "test_OMChart"
DateErrorMessage = "test_dateErrorMessage"
EEBubblePopup = "test_eeBubblePopUp"
TreeElement = "test_treeElement"
EmployeeColorIcon = "test_employeeColorIcon"
WidgetTitle = "test_widget_text"
CloseIcon = "test_close_icon"




